id: PC7C190B7
initial_creation_type: input
source_metadata:
  title: Tsongkhapa Lobzang Drakpa Series
  language: es
  description: 'Texts by and about the great master Tsongkhapa Lobzang Drakpa (tsong
    kha pa blo bzang grags pa) (1357–1419), founder of the Gelug school:'
  volume:
    aab7dccd6f1f4980985bcf0d608c8eef:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    888aa09feab64ab0831788578b8bf060:
      title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
      parent: Guru Yoga
    e04a963cdb2f425280e8e4851ee6d591:
      title: Three Principal Aspects of the Path
      parent: Mind Training
    66cf62a7d6a2475cb33d464df2602eb9:
      title: Praise to Mañjughoṣa
      parent: Praise
    3633ebc0c44447289e26983556596643:
      title: 'The Flower of Faith: Praise to the Great Lord Guru Tsongkhapa'
      parent: Praise
    0dfc03e09d0f4edb95fbfb836f743b0a:
      title: Aspiration for the Stages of the Path
      parent: Prayers
    852660657f0646b1a7686992a09ce8ad:
      title: Prayer to Rendawa Shönnu Lodrö
      parent: Prayers
    afa885f67af34134a75057d83cf2dba1:
      title: The Foundation of All Qualities
      parent: Prayers
created_at: '2022-03-01T01:55:51.973646'
last_modified_at: '2022-03-01T01:55:51.973649'
